/**
 * Disclaimer text
 * Last updated: Dec 31, 2025
 */
export const disclaimerText = `Disclaimer
Last updated: Dec 31, 2025 1:22 AM

Please read this Disclaimer carefully before using the RecoverySky App application (the "Application") operated by RecoverySky Org, a(n) Not For Profit formed in Delaware, United States ("us, we, our") as this Disclaimer contains important information regarding limitations of our liability. Your access to and use of the Application is conditional upon your acceptance of and compliance with this Disclaimer. This Disclaimer applies to everyone, including but not limited to visitors, users, and others, who wish to access or use the Application.

By accessing or using the Application, you agree to be bound by this Disclaimer. If you disagree with any part of this Disclaimer, then you do not have our permission to access or use the Application.

Testimonials, reviews and endorsements disclaimer
Any testimonials, reviews and endorsements displayed on this Application are received via text, audio or video submissions. They are real-life, individual experiences of those who have used our products or services. The results obtained by these individuals are not necessarily typical to what other consumers may achieve or experience. The testimonials, reviews and endorsements are displayed verbatim except for correction of grammatical and spelling errors and may have been shortened or edited for clarity. We are not responsible for the testimonials, reviews and endorsements displayed on this Application and do not necessarily share the opinions, views or commentary of such testimonials, reviews and endorsements.

The persons providing such testimonials, reviews and endorsements have not been compensated for doing so. The individuals providing the testimonials, reviews and endorsements displayed on this Application are not employed by us.

Health information disclaimer
This Application displays information about health. This information is presented for educational and entertainment purposes only and does not substitute the advice of a healthcare professional. This information is not to be used for any diagnostic, treatment, prevention or curative purposes. The provision of this information does not establish nor create any healthcare professional-patient relationship or any physician-patient relationship.

Recovery information disclaimer
This Application includes features, including but not limited to the Sky Agent Meeting Guide, that provide information, suggestions, and guidance related to addiction recovery and related topics. This information is presented for educational and informational purposes only and does not substitute the advice of a licensed mental health professional, addiction counselor, medical provider, or sponsor.

The Sky Agent Meeting Guide and any other automated or AI-assisted features within this Application are not qualified to provide mental health treatment, recovery counseling, or personalized advice. Any suggestions, meeting topics, discussion prompts, or other content generated by these features should not be relied upon as professional guidance or as a substitute for participation in established recovery programs, professional treatment, or peer support.

Recovery is a deeply personal journey, and what works for one individual may not be appropriate for another. You should always consult with qualified professionals, your sponsor, or trusted members of your recovery community before making decisions about your recovery plan.
You agree that you assume all responsibility when choosing to act on any recovery-related information provided on this Application. We make no representations or warranties regarding the accuracy, completeness, or suitability of this information for your individual circumstances.

You should always consult with a healthcare professional prior to implementing any changes to your health routine to ensure that doing so is safe for you. You agree that you assume all responsibility when choosing to act on any health information provided on this Application.

No legal advice
The information displayed on this Application is provided for informational and educational purposes and is not intended as legal advice. You should always consult with a lawyer for help with your specific legal needs and issues.

Changes
We reserve the right to make changes to this Disclaimer at any time without any prior notice to you.

Questions
If you have any questions about this Disclaimer, please contact us at admin@recoverysky.org.`
